version: '3.7'

services:
  django:
    build: .
    volumes:
      - static_volume:/usr/src/static
      - media_volume:/usr/src/media
      - uploads_volume:/usr/src/uploads
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=wwwapp.settings_prod
      - MEDIA_ROOT=/usr/src/media
      - SENDFILE_ROOT=/usr/src/uploads
      - SECRET_KEY=test123
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=${SOCIAL_AUTH_GOOGLE_OAUTH2_KEY}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}
      - SOCIAL_AUTH_FACEBOOK_KEY=${SOCIAL_AUTH_FACEBOOK_KEY}
      - SOCIAL_AUTH_FACEBOOK_SECRET=${SOCIAL_AUTH_FACEBOOK_SECRET}
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=aplikacjawww
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/static
      - media_volume:/usr/share/nginx/media
      - uploads_volume:/usr/share/nginx/uploads
      - ${INTERNETY:-/dev/null}:/usr/share/nginx/internety
    ports:
      - 8000:8000
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
  uploads_volume:
