# Generated by Django 3.1.4 on 2021-01-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='(w URLach)', unique=True, verbose_name='Nazwa')),
                ('title', models.CharField(max_length=50, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, help_text='Krótki opis wyświetlany na górze formulaza', max_length=100000, verbose_name='Opis')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Widoczny?')),
            ],
            options={
                'verbose_name': 'formularz',
                'verbose_name_plural': 'formularze',
                'permissions': [('see_form_results', 'Can see form results')],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tekst pytania')),
                ('data_type', models.CharField(choices=[('n', 'Liczba'), ('s', 'Tekst'), ('t', 'Tekst (wiele linii)'), ('d', 'Data'), ('C', 'Lista rozwijana'), ('c', 'Wybór jednokrotny'), ('m', 'Wybór wielokrotny'), ('P', 'PESEL')], max_length=1, verbose_name='Typ odpowiedzi')),
                ('is_required', models.BooleanField(default=True, verbose_name='Wymagane?')),
                ('is_locked', models.BooleanField(default=False, help_text='Zablokuj możliwość edycji odpowiedzi na to pytanie', verbose_name='Edycja zablokowana?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='wwwforms.form', verbose_name='Formularz')),
            ],
            options={
                'verbose_name': 'pytanie',
                'verbose_name_plural': 'pytania',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tekst opcji')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='wwwforms.formquestion')),
            ],
            options={
                'verbose_name': 'opcja',
                'verbose_name_plural': 'opcje',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='form',
            name='arrival_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wwwforms.formquestion', verbose_name='Data przyjazdu'),
        ),
        migrations.AddField(
            model_name='form',
            name='departure_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wwwforms.formquestion', verbose_name='Data wyjazdu'),
        ),
        migrations.CreateModel(
            name='FormQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changed', models.DateTimeField(auto_now=True, null=True)),
                ('value_number', models.IntegerField(blank=True, null=True)),
                ('value_string', models.CharField(blank=True, max_length=100000, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('question', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wwwforms.formquestion')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('value_choices', models.ManyToManyField(blank=True, related_name='_formquestionanswer_value_choices_+', to='wwwforms.FormQuestionOption')),
            ],
            options={
                'verbose_name': 'odpowiedź',
                'verbose_name_plural': 'odpowiedzi',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
