# Generated by Django 3.1.4 on 2021-01-02 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='(w URLach)', unique=True, verbose_name='Nazwa')),
                ('title', models.CharField(max_length=50, verbose_name='Tytuł')),
            ],
            options={
                'verbose_name': 'formularz',
                'verbose_name_plural': 'formularze',
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tekst pytania')),
                ('data_type', models.CharField(choices=[('n', 'Liczba'), ('s', 'Tekst'), ('t', 'Tekst (wiele linii)'), ('d', 'Data'), ('P', 'PESEL')], max_length=1, verbose_name='Typ odpowiedzi')),
                ('is_required', models.BooleanField(default=True, verbose_name='Wymagane?')),
                ('form', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='wwwforms.form')),
            ],
            options={
                'verbose_name': 'pytanie',
                'verbose_name_plural': 'pytania',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='arrival_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wwwforms.formquestion', verbose_name='Data przyjazdu'),
        ),
        migrations.AddField(
            model_name='form',
            name='departure_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wwwforms.formquestion', verbose_name='Data wyjazdu'),
        ),
        migrations.CreateModel(
            name='FormQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_number', models.IntegerField(blank=True, null=True)),
                ('value_string', models.CharField(blank=True, max_length=100000, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('question', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wwwforms.formquestion')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'odpowiedź',
                'verbose_name_plural': 'odpowiedzi',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
