# Generated by Django 3.1.4 on 2021-01-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'ordering': ['order'], 'verbose_name': 'pytanie', 'verbose_name_plural': 'pytania'},
        ),
        migrations.AddField(
            model_name='formquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
