# Generated by Django 3.2.11 on 2022-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='data_type',
            field=models.CharField(choices=[('n', 'Liczba'), ('s', 'Tekst'), ('t', 'Tekst (wiele linii)'), ('d', 'Data'), ('C', 'Lista rozwijana'), ('c', 'Wybór jednokrotny'), ('m', 'Wybór wielokrotny'), ('P', 'PESEL'), ('p', 'Numer telefonu')], max_length=1, verbose_name='Typ odpowiedzi'),
        ),
    ]
