# Generated by Django 3.2.12 on 2022-04-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0002_add_phone_number_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='form',
            name='departure_date',
        ),
    ]
