# Generated by Django 3.1.4 on 2021-01-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0003_add_see_results_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Widoczny?'),
        ),
    ]
