# Generated by Django 5.2.17 on 2026-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0003_move_special_field_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestionanswer',
            name='value_choices',
            field=models.ManyToManyField(blank=True, related_name='+', to='wwwforms.formquestionoption'),
        ),
    ]
