# Generated by Django 3.1.4 on 2021-01-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0004_form_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Zablokuj możliwość edycji odpowiedzi na to pytanie', verbose_name='Edycja zablokowana?'),
        ),
    ]
