# Generated by Django 3.1.4 on 2021-01-02 21:35

from django.db import migrations, models


def set_to_null(apps, schema_editor):
    # The values which already existed should have last_changed set to NULL
    FormQuestionAnswer = apps.get_model('wwwforms', 'FormQuestionAnswer')
    FormQuestionAnswer.objects.update(last_changed=None)


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0005_formquestion_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestionanswer',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(set_to_null, migrations.RunPython.noop),
    ]
