# Generated by Django 3.1.4 on 2021-01-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0006_formquestionanswer_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.CharField(blank=True, help_text='Krótki opis wyświetlany na górze formulaza', max_length=1000, verbose_name='Opis'),
        ),
    ]
