# Generated by Django 3.1.4 on 2021-01-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0007_form_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='data_type',
            field=models.CharField(choices=[('n', 'Liczba'), ('s', 'Tekst'), ('t', 'Tekst (wiele linii)'), ('d', 'Data'), ('C', 'Lista rozwijana'), ('c', 'Wybór jednokrotny'), ('m', 'Wybór wielokrotny'), ('P', 'PESEL')], max_length=1, verbose_name='Typ odpowiedzi'),
        ),
        migrations.CreateModel(
            name='FormQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tekst opcji')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='wwwforms.formquestion')),
            ],
            options={
                'verbose_name': 'opcja',
                'verbose_name_plural': 'opcje',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='formquestionanswer',
            name='value_choices',
            field=models.ManyToManyField(blank=True, related_name='_formquestionanswer_value_choices_+', to='wwwforms.FormQuestionOption'),
        ),
    ]
