# Generated by Django 3.1.4 on 2021-01-04 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0008_add_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='wwwforms.form', verbose_name='Formularz'),
        ),
    ]
