# Generated by Django 3.1.5 on 2021-01-30 23:19

from django.db import migrations


def forwards_func(apps, schema_editor):
    from cms.api import create_page, add_plugin, publish_page
    Article = apps.get_model('wwwapp', 'Article')

    Site = apps.get_model('sites', 'Site')
    Site.objects.create(domain='warsztatywww.pl', name='Wakacyjne Warsztaty Wielodyscyplinarne')

    index_article = Article.objects.get(name='index')
    index_page = create_page(title='Strona główna', template='page_index.html', language='pl', slug='index', in_navigation=True)
    add_plugin(index_page.placeholders.get(slot='header_image'), 'Bootstrap4PicturePlugin', 'pl', external_picture='https://warsztatywww.pl/media/images/articles/index/64f5e2127a13b64d5624058ee812904d297e8e15d81a449dafda59563a18ed64.jpg')
    add_plugin(index_page.placeholders.get(slot='left_of_facebook_embed'), 'TextPlugin', 'pl', body='''
<p><span style="font-size: 18px;"><strong>16. Wakacyjne Warsztaty Wielodyscyplinarne</strong></span> odbyły się 3-17 lipca 2020 roku.</p>

<p>Chętnych do poprowadzenia zajęć zapraszamy do działu&nbsp;<strong><a href="/article/dla-prowadzacych/">dla prowadzących</a></strong>. Chętnych do wzięcia udziału w kolejnej edycji kierujemy&nbsp;do działu <strong><a href="/article/dla-uczestnikow/">dla uczestnik&oacute;w</a></strong>.</p>

<h2><a href="/program/">Program</a></h2>

<p>&nbsp;</p>

<p><strong><span style="font-size: 18px;">Terminy WWW16 (2020)</span></strong></p>

<table border="0" cellspacing="0" style="width: 100%; border-collapse: collapse;">
	<tbody>
		<tr>
			<td style="width: 32.1044%; padding: 0.25em;"><strong>Do 1 kwietnia</strong></td>
			<td style="width: 67.9078%; padding: 0.25em;">Pojawiają się strony warsztat&oacute;w i zadania kwalifikacyjne</td>
		</tr>
		<tr>
			<td style="width: 32.1044%; padding: 0.25em;"><strong>1 kwietnia - <span style="text-decoration: line-through;">17 maja</span> 20 maja</strong></td>
			<td style="width: 67.9078%; padding: 0.25em;">Czas na rozwiązywanie zadań kwalifikacyjnych przez uczestnik&oacute;w</td>
		</tr>
		<tr>
			<td style="width: 32.1044%; padding: 0.25em;"><strong>4 czerwca</strong></td>
			<td style="width: 67.9078%; padding: 0.25em;">Informacja o kwalifikacji uczestnik&oacute;w</td>
		</tr>
		<tr>
			<td style="width: 32.1044%; padding: 0.25em;"><strong>3 - 17 lipca</strong></td>
			<td style="width: 67.9078%; padding: 0.25em;">Zdalne warsztaty</td>
		</tr>
	</tbody>
</table>
''')
    add_plugin(index_page.placeholders.get(slot='content'), 'TextPlugin', 'pl', body='''
<h2>O Warsztatach</h2>

<p>Wakacyjne Warsztaty Wielodyscyplinarne to coroczne wydarzenie przeznaczone dla licealist&oacute;w zainteresowanych <span class="_4yxo"><strong>matematyką</strong>, <strong>informatyką</strong>, <strong>fizyką</strong>, <strong>astronomią </strong></span>lub<strong><span class="_4yxo"> biologią</span></strong>. Zajęcia prowadzi grupa zaprzyjaźnionych student&oacute;w z całej polski pod patronatem Społeczności MIMUW, Miasta Zabrze i Uniwersytetu Warszawskiego.</p>

<p>Każdy uczestnik Warsztat&oacute;w może wybrać kilka spośr&oacute;d kilkunastu propozycji kilkudniowych blok&oacute;w zajęć. Zajęcia odbywają się w małych grupach i mają charakter warsztatowy. Obok wykład&oacute;w bardzo istotna jest część praktyczna &ndash; rozwiązywanie zadań, pisanie program&oacute;w. Wieczorami można uczestniczyć w &quot;luźnych&quot; wykładach i prezentacjach, niezwiązanych z żadnym blokiem zajęć, i poruszających r&oacute;żne ciekawe tematy z, ale r&oacute;wnież spoza, zakresu nauk ścisłych &ndash;&nbsp;lub samemu wygłosić taki wykład! A pozanaukowo &ndash;&nbsp;integracja, gry i zabawy; dla chętnych przeprowadzamy przyspieszony kurs brydża i go, bardziej zaawansowani gracze mogą spr&oacute;bować swoich sił w turnieju, a każdy może zagrać w seta, rpg, plansz&oacute;wki, czy pośpiewać ogniskowe piosenki.</p>

<p>W związku z Warsztatami powstał&nbsp;<a href="/article/drogowskaz/">Drogowskaz Pasjonata</a>&nbsp;&ndash;&nbsp;<strong>poradnik dla młodych zdolnych licealist&oacute;w</strong>, kt&oacute;rzy chcą rozwijać swoje talenty (niezależnie czy byli/będą na WWW czy nie). Tekst polecamy zar&oacute;wno powyższym, jak i osobom, kt&oacute;re mają z nimi styczność (rodzice, nauczyciele, tutorzy).</p>

<p>Zachęcamy do lektury:&nbsp;<strong><a href="/article/en-indie-camp-for-hs-geeks/">An independent camp for high school geeks</a></strong>&nbsp;&ndash; tekst po angielsku o tym, co to są&nbsp;Wakacyjne Warsztaty Wielodyscyplinarne, co jest w nich szczeg&oacute;lnego i jak tę&nbsp;wiedzę można wykorzystać.</p>

<p>Chętnych do&nbsp;<strong>prowadzenia zajęć</strong>&nbsp;zachęcamy do zapoznania się z&nbsp;<a href="/article/dla-prowadzacych/">informacjami dla prowadzących</a>.</p>

<p>Zobacz też <a href="/article/historia/">program poprzednich warsztat&oacute;w</a>&nbsp;i <a href="/gallery/">zdjęcia z poprzednich edycji</a>.</p>
''')
    index_page.set_as_homepage()
    index_page.publish('pl')

    for article in Article.objects.exclude(name__in=['index', 'template_for_workshop_page']).all():
        page = create_page(title=article.title, template='page_basic.html', language='pl', slug=article.name, in_navigation=article.on_menubar)
        add_plugin(page.placeholders.get(slot='content'), 'TextPlugin', 'pl', body=article.content)
        page.publish('pl')

    Article.objects.exclude(name='template_for_workshop_page').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0072_change_upload_storage'),
        ('menus', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_text_ckeditor', '0004_auto_20160706_1339'),
        ('djangocms_picture', '0011_auto_20190314_1536'),
        ('bootstrap4_picture', '0004_auto_20190703_0831'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
