# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0058_auto_20200211_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
