# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-16 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0061_reverse_userprofile_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='k8s_password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='k8s_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='owncloud_password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='owncloud_user',
        ),
    ]
