# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0063_migrate_away_from_python_allaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopuserprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Z', 'Zaakceptowany'), ('O', 'Odrzucony'), ('X', 'Odwołany')], default=None, max_length=10, null=True),
        ),
    ]
