# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from django.conf import settings
from django.utils.datetime_safe import datetime


def forwards_func(apps, schema_editor):
    Camp = apps.get_model("wwwapp", "Camp")
    WorkshopType = apps.get_model("wwwapp", "WorkshopType")
    db_alias = schema_editor.connection.alias

    for year in WorkshopType.objects.using(db_alias).values_list('year', flat=True).distinct():
        camp, created = Camp.objects.using(db_alias).get_or_create(year=year)
        if created and hasattr(settings, 'CURRENT_YEAR') and camp.year == settings.CURRENT_YEAR:
            if hasattr(settings, 'WORKSHOPS_START_DATE'):
                camp.start_date = settings.WORKSHOPS_START_DATE
            if hasattr(settings, 'WORKSHOPS_END_DATE'):
                camp.end_date = settings.WORKSHOPS_END_DATE
            camp.save()

    # At least one Camp object must always exist
    if not Camp.objects.using(db_alias).exists():
        Camp.objects.using(db_alias).create(year=datetime.today().year)


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0065_auto_20200820_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('proposal_end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year'],
                'get_latest_by': 'year',
            },
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='resourceyearpermission',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwwapp.Camp'),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwwapp.Camp'),
        ),
        migrations.AlterField(
            model_name='workshoptype',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwwapp.Camp'),
        ),
        migrations.AlterField(
            model_name='workshopuserprofile',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wwwapp.Camp'),
        ),
    ]
