# Generated by Django 3.1 on 2020-08-22 08:33

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Workshop = apps.get_model("wwwapp", "Workshop")
    db_alias = schema_editor.connection.alias

    for workshop in Workshop.objects.using(db_alias).all():
        workshop.year = workshop.type.year
        workshop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0067_auto_20200820_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='wwwapp.camp'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='wwwapp.camp'),
        ),
        migrations.AlterUniqueTogether(
            name='workshop',
            unique_together={('year', 'name')},
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='year',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='wwwapp.camp'),
        ),
        migrations.AlterField(
            model_name='workshoptype',
            name='year',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='wwwapp.camp'),
        ),
    ]
