# Generated by Django 3.1.4 on 2021-01-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0069_migrate_userinfo_to_wwwforms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
