# Generated by Django 3.1.5 on 2021-01-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0070_add_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='solution_uploads_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
