# Generated by Django 3.1.5 on 2021-01-30 19:06

import django.core.files.storage
from django.db import migrations, models
import wwwapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0071_enable_uploads_for_new_workshops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='/home/krzys_h/Pulpit/aplikacjawww/uploads'), upload_to=wwwapp.models.solutions_dir, verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='qualification_problems',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='/home/krzys_h/Pulpit/aplikacjawww/uploads'), upload_to='qualification'),
        ),
    ]
