# Generated by Django 3.1.7 on 2021-03-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0072_article_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopparticipant',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='workshopparticipant',
            name='qualification_result',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Liczba punktów'),
        ),
    ]
