# Generated by Django 3.2.11 on 2022-02-02 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0075_auto_20210520_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkshopUserProfile',
            new_name='CampParticipant',
        ),
        migrations.AlterField(
            model_name='campparticipant',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_participation', to='wwwapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='campparticipant',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='wwwapp.camp'),
        ),
        migrations.AlterUniqueTogether(
            name='campparticipant',
            unique_together={('user_profile', 'year')},
        ),
    ]
