# Generated by Django 3.2.11 on 2022-02-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0076_rename_workshopuserprofile_campparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopparticipant',
            old_name='participant',
            new_name='user_profile',
        ),
        migrations.AlterUniqueTogether(
            name='workshopparticipant',
            unique_together={('workshop', 'user_profile')},
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='participants',
        ),
        migrations.AlterField(
            model_name='workshopparticipant',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_participation', to='wwwapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='workshopparticipant',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='wwwapp.workshop'),
        ),
    ]
