# Generated by Django 3.2.11 on 2022-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0078_cleanup_article_and_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='program_finalized',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camp',
            name='program_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
