# Generated by Django 3.2.11 on 2022-02-02 15:47

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    WorkshopParticipant = apps.get_model("wwwapp", "WorkshopParticipant")
    CampParticipant = apps.get_model("wwwapp", "CampParticipant")
    for item in WorkshopParticipant.objects.all():
        item.camp_participation, _ = CampParticipant.objects.get_or_create(user_profile=item.user_profile, year=item.workshop.year)
        item.save()


def reverse_func(apps, schema_editor):
    WorkshopParticipant = apps.get_model("wwwapp", "WorkshopParticipant")
    CampParticipant = apps.get_model("wwwapp", "CampParticipant")
    for item in WorkshopParticipant.objects.all():
        item.user_profile = item.camp_participation.user_profile
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0079_camp_program_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopparticipant',
            name='camp_participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_participation', to='wwwapp.campparticipant'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='workshopparticipant',
            name='camp_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_participation', to='wwwapp.campparticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='workshopparticipant',
            unique_together={('workshop', 'camp_participation')},
        ),
        migrations.RemoveField(
            model_name='workshopparticipant',
            name='user_profile',
        ),
    ]
