# Generated by Django 3.2.11 on 2022-02-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0080_workshopparticipant_camp_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopparticipant',
            name='camp_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_participation', to='wwwapp.campparticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='workshopparticipant',
            unique_together={('workshop', 'camp_participation')},
        ),
        migrations.RemoveField(
            model_name='workshopparticipant',
            name='user_profile',
        ),
    ]
