# Generated by Django 3.2.11 on 2022-02-02 18:57

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    UserProfile = apps.get_model("wwwapp", "UserProfile")
    Camp = apps.get_model("wwwapp", "Camp")
    for item in UserProfile.objects.all():
        if not item.cover_letter:
            continue

        camp_participation = item.camp_participation.order_by('-year__year').first()
        if not camp_participation:
            camp_participation = item.camp_participation.create(year=Camp.objects.latest())
        camp_participation.cover_letter = item.cover_letter
        camp_participation.save()


def reverse_func(apps, schema_editor):
    UserProfile = apps.get_model("wwwapp", "UserProfile")
    for item in UserProfile.objects.all():
        camp_participation = item.camp_participation.order_by('-year__year').first()
        if camp_participation:
            item.cover_letter = camp_participation.cover_letter
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0081_workshopparticipant_camp_participation_post_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='campparticipant',
            name='cover_letter',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_letter',
        ),
    ]
