# Generated by Django 3.2.12 on 2022-04-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0082_campparticipant_cover_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_letter',
        ),
    ]
