# Generated by Django 3.2.12 on 2022-04-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0003_move_special_field_handling'),
        ('wwwapp', '0082_campparticipant_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='form_question_arrival_date',
            field=models.ForeignKey(blank=True, help_text='Pole typu Data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wwwforms.formquestion', verbose_name='Data przyjazdu'),
        ),
        migrations.AddField(
            model_name='camp',
            name='form_question_departure_date',
            field=models.ForeignKey(blank=True, help_text='Pole typu Data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wwwforms.formquestion', verbose_name='Data wyjazdu'),
        ),
        migrations.AddField(
            model_name='camp',
            name='forms',
            field=models.ManyToManyField(related_name='years', to='wwwforms.Form', verbose_name='Formularze'),
        ),
    ]
