# Generated by Django 3.2.12 on 2022-04-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0003_move_special_field_handling'),
        ('wwwapp', '0083_move_special_field_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='form_question_birth_date',
            field=models.ForeignKey(blank=True, help_text='Pole typu Data lub PESEL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wwwforms.formquestion', verbose_name='Data urodzenia'),
        ),
    ]
