# Generated by Django 3.2.15 on 2022-08-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0084_camp_form_question_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'base_manager_name': 'objects', 'permissions': (('see_all_workshops', 'Can see all workshops'), ('edit_all_workshops', 'Can edit all workshops'), ('change_workshop_status', 'Can change workshop status'))},
        ),
        migrations.AlterModelOptions(
            name='workshopparticipant',
            options={'base_manager_name': 'objects'},
        ),
    ]
