# Generated by Django 3.2.15 on 2023-01-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0085_auto_20220822_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('see_all_users', 'Can see all users'), ('export_workshop_registration', 'Can download workshop registration data'), ('use_secret_notes', 'Can see and edit secret notes about users')]},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secret_notes',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
    ]
