# Generated by Django 3.2.15 on 2023-01-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwforms', '0003_move_special_field_handling'),
        ('wwwapp', '0086_auto_20230102_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='forms',
            field=models.ManyToManyField(blank=True, related_name='years', to='wwwforms.Form', verbose_name='Formularze'),
        ),
    ]
