# Generated by Django 3.2.15 on 2023-02-23 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0087_camp_forms_not_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampInterestEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_via_email', to='wwwapp.camp')),
            ],
            options={
                'unique_together': {('year', 'email')},
            },
        ),
    ]
