# Generated by Django 3.2.18 on 2025-04-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0088_campinterestemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopparticipant',
            options={'base_manager_name': 'objects', 'ordering': ['id']},
        ),
    ]
