# Generated by Django 3.2.18 on 2026-04-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0089_alter_workshopparticipant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshoptype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshoptype',
            name='plural_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workshoptype',
            name='year',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_types', to='wwwapp.camp'),
        ),
    ]
