# Generated by Django 3.2.18 on 2026-07-24 20:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wwwapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwwapp', '0090_workshop_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('ASSOCIATION', 'Stowarzyszenie'), ('OTHER', 'Inne')], max_length=11)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('executed_date', models.DateField()),
                ('account_number', models.CharField(max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to='wwwapp.camp')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_allocated', models.PositiveIntegerField(default=0)),
                ('camp', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_sequence', to='wwwapp.camp')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(storage=wwwapp.models.UploadStorage(), upload_to='invoices')),
                ('document_number', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('invoice_type', models.CharField(choices=[('KSEF', 'KSeF'), ('OUTSIDE_KSEF', 'Poza KSeF'), ('RECEIPT_WITH_NIP', 'Paragon z NIP'), ('NON_ACCOUNTING_RECEIPT', 'Paragon nieksięgowy')], max_length=24)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('RECEIVED', 'Otrzymana'), ('APPROVED', 'Zatwierdzona'), ('PROCESSED', 'Przetworzona'), ('REJECTED', 'Odrzucona')], default='RECEIVED', max_length=12)),
                ('internal_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_changed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_changed_invoices', to=settings.AUTH_USER_MODEL)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='wwwapp.camp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_all_costs', 'Can view all costs'), ('approve_costs', 'Can approve or reject costs'), ('export_costs', 'Can export costs'), ('process_costs', 'Can process costs'), ('register_reimbursements', 'Can register reimbursements'), ('view_cost_statistics', 'Can view cost statistics')),
            },
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('WORKSHOPS', 'Warsztaty'), ('OUTINGS', 'Wyjścia'), ('LUNCHES', 'Obiady'), ('BREAKFASTS', 'Śniadania'), ('REGULAR_PURCHASES', 'Zakupy stałe'), ('SUPPORTING_AND_TECHNICAL_MATERIALS', 'Materiały pomocnicze i techniczne')], max_length=36)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='wwwapp.invoice')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='wwwapp.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_details', to='wwwapp.camp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'camp')},
            },
        ),
    ]
