# Generated by Django 3.2.18 on 2026-07-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0090_workshop_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampGoogleSheetsIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('participants_sheet_id', models.BigIntegerField(blank=True, null=True)),
                ('lecturers_sheet_id', models.BigIntegerField(blank=True, null=True)),
                ('workshops_sheet_id', models.BigIntegerField(blank=True, null=True)),
                ('dirty', models.BooleanField(default=False)),
                ('next_sync_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=2000)),
                ('camp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='google_sheets_integration',
                                               to='wwwapp.camp')),
            ],
        ),
        migrations.AddIndex(
            model_name='campgooglesheetsintegration',
            index=models.Index(fields=['enabled', 'dirty', 'next_sync_at'],
                               name='wwwapp_camp_enabled_a3dcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='campgooglesheetsintegration',
            index=models.Index(fields=['claimed_at'], name='wwwapp_camp_claimed_82b993_idx'),
        ),
    ]
