# Generated by Django 3.2.18 on 2026-07-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwwapp', '0091_invoice_takeover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': (('view_all_costs', 'Can view all costs'), ('approve_costs', 'Can approve or reject costs'), ('process_costs', 'Can process costs'), ('register_reimbursements', 'Can register reimbursements'))},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='admin_changed_at',
            new_name='admin_modified_at',
        ),
        migrations.RenameField(
            model_name='reimbursement',
            old_name='executed_date',
            new_name='execution_date',
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='account_number_snapshot',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='admin_changed_by',
            new_name='admin_modified_by',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settlementdetails',
            name='account_number',
            field=models.CharField(max_length=64),
        ),
    ]
