# Generated by Django 3.2.18 on 2026-07-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wwwapp', '0092_auto_20260730_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='admin_modified_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='admin_modified_invoices',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
