# Generated by Django 3.2.18 on 2026-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0092_separate_invoice_numbering_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesequence',
            name='series',
            field=models.CharField(
                choices=[
                    ('KSEF', 'KSeF'),
                    ('OUTSIDE_KSEF', 'Poza KSeF'),
                    ('RECEIPT_WITH_NIP', 'Paragon z NIP'),
                    ('NON_ACCOUNTING_RECEIPT', 'Paragon nieksięgowy'),
                ],
                max_length=24,
            ),
        ),
        migrations.RemoveConstraint(
            model_name='invoicesequence',
            name='unique_invoice_sequence_series_per_camp',
        ),
        migrations.RenameField(
            model_name='invoicesequence',
            old_name='series',
            new_name='invoice_type',
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.UniqueConstraint(
                fields=('camp', 'invoice_type'),
                name='unique_invoice_sequence_type_per_camp',
            ),
        ),
    ]
