# Generated by Django 3.2.18 on 2026-07-30

from django.db import migrations, models
import wwwapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0093_alter_invoice_admin_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementdetails',
            name='account_number',
            field=models.CharField(
                max_length=64,
                validators=[wwwapp.models.validate_polish_account_number],
            ),
        ),
    ]
