# Generated by Django 3.2.18 on 2026-08-13 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0095_renumber_invoices_to_fvp_and_remove_invoicesequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopparticipant',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ocena'),
        ),
    ]
